import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: "1rem", sm: "1.5rem", lg: "2rem" },
      screens: { "2xl": "1400px" },
    },
    extend: {
      screens: { xs: "480px" },
      minHeight: { touch: "44px" },
      minWidth:  { touch: "44px" },
      /* Plans — tokens de DESIGN.md § 6. Plus aucun z-index en dur. */
      zIndex: {
        base:        "var(--z-base)",
        sticky:      "var(--z-sticky)",
        bar:         "var(--z-bar)",
        player:      "var(--z-player)",
        overlay:     "var(--z-overlay)",
        celebration: "var(--z-celebration)",
      },
      spacing: {
        "safe-top":    "env(safe-area-inset-top)",
        "safe-bottom": "env(safe-area-inset-bottom)",
        "safe-left":   "env(safe-area-inset-left)",
        "safe-right":  "env(safe-area-inset-right)",
      },
      fontFamily: {
        // Les familles viennent de `--font-display` / `--font-text` : le drapeau
        // de refonte les bascule sans toucher à une seule classe.
        sans:    ['var(--font-text)'],
        display: ['var(--font-display)'],
        body:    ['var(--font-text)'],
        mono:    ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
        slogan:  ['var(--font-slogan)'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary:     { DEFAULT: "hsl(var(--primary))",     foreground: "hsl(var(--primary-foreground))" },
        secondary:   { DEFAULT: "hsl(var(--secondary))",   foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted:       { DEFAULT: "hsl(var(--muted))",       foreground: "hsl(var(--muted-foreground))" },
        accent:      { DEFAULT: "hsl(var(--accent))",      foreground: "hsl(var(--accent-foreground))" },
        popover:     { DEFAULT: "hsl(var(--popover))",     foreground: "hsl(var(--popover-foreground))" },
        card:        { DEFAULT: "hsl(var(--card))",        foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        cia: {
          blue: {
            50:  'hsl(var(--cia-blue-50))',
            100: 'hsl(var(--cia-blue-100))',
            200: 'hsl(var(--cia-blue-200))',
            300: 'hsl(var(--cia-blue-300))',
            400: 'hsl(var(--cia-blue-400))',
            500: 'hsl(var(--cia-blue-500))',
            600: 'hsl(var(--cia-blue-600))',
            700: 'hsl(var(--cia-blue-700))',
            800: 'hsl(var(--cia-blue-800))',
            900: 'hsl(var(--cia-blue-900))',
          },
          gold: {
            DEFAULT: 'hsl(var(--cia-gold-500))',
            50:  'hsl(var(--cia-gold-50))',
            100: 'hsl(var(--cia-gold-100))',
            200: 'hsl(var(--cia-gold-200))',
            300: 'hsl(var(--cia-gold-300))',
            400: 'hsl(var(--cia-gold-400))',
            500: 'hsl(var(--cia-gold-500))',
            600: 'hsl(var(--cia-gold-600))',
            700: 'hsl(var(--cia-gold-700))',
            800: 'hsl(var(--cia-gold-800))',
            900: 'hsl(var(--cia-gold-900))',
          },
          red: {
            50:  'hsl(var(--cia-red-50))',
            100: 'hsl(var(--cia-red-100))',
            200: 'hsl(var(--cia-red-200))',
            300: 'hsl(var(--cia-red-300))',
            400: 'hsl(var(--cia-red-400))',
            500: 'hsl(var(--cia-red-500))',
            600: 'hsl(var(--cia-red-600))',
            700: 'hsl(var(--cia-red-700))',
            800: 'hsl(var(--cia-red-800))',
            900: 'hsl(var(--cia-red-900))',
          },
          spark: {
            light: 'hsl(var(--cia-spark-light))',
            mid:   'hsl(var(--cia-spark-mid))',
            deep:  'hsl(var(--cia-spark-deep))',
            ember: 'hsl(var(--cia-spark-ember))',
          },
          /* Legacy aliases */
          navy:        "hsl(var(--cia-navy))",
          "navy-light": "hsl(var(--cia-navy-light))",
          sky:         "hsl(var(--cia-sky))",
          sand:        "hsl(var(--cia-sand))",
          success:     "hsl(var(--cia-success))",
          warning:     "hsl(var(--cia-warning))",
          xp:          "hsl(var(--cia-xp))",
          streak:      "hsl(var(--cia-streak))",
          gems:        "hsl(var(--cia-gems))",
          bonus:       "hsl(var(--cia-bonus))",
        },
        ink: {
          50:  'hsl(var(--ink-50))',
          100: 'hsl(var(--ink-100))',
          200: 'hsl(var(--ink-200))',
          300: 'hsl(var(--ink-300))',
          400: 'hsl(var(--ink-400))',
          500: 'hsl(var(--ink-500))',
          600: 'hsl(var(--ink-600))',
          700: 'hsl(var(--ink-700))',
          800: 'hsl(var(--ink-800))',
          900: 'hsl(var(--ink-900))',
        },
        success: {
          50:  'hsl(145 70% 95%)',
          100: 'hsl(145 65% 86%)',
          500: 'hsl(var(--success-500))',
          600: 'hsl(var(--success-600))',
          700: 'hsl(var(--success-700))',
        },
        warning: {
          50:  'hsl(38 100% 94%)',
          100: 'hsl(38 95% 84%)',
          500: 'hsl(var(--warning-500))',
          600: 'hsl(var(--warning-600))',
          700: 'hsl(var(--warning-700))',
        },
        error: {
          50:  'hsl(348 70% 95%)',
          100: 'hsl(349 71% 85%)',
          500: 'hsl(var(--error-500))',
          600: 'hsl(var(--error-600))',
          700: 'hsl(var(--error-700))',
        },
        info: {
          50:  'hsl(210 100% 95%)',
          100: 'hsl(210 100% 86%)',
          500: 'hsl(var(--info-500))',
          600: 'hsl(var(--info-600))',
          700: 'hsl(var(--info-700))',
        },
        xp:     { DEFAULT: 'hsl(var(--xp-500))',     500: 'hsl(var(--xp-500))' },
        streak: { DEFAULT: 'hsl(var(--streak-500))', 500: 'hsl(var(--streak-500))' },
        gems:   { DEFAULT: 'hsl(var(--gems-500))',   500: 'hsl(var(--gems-500))' },
        bonus:  { DEFAULT: 'hsl(var(--bonus-500))',  500: 'hsl(var(--bonus-500))' },
        league: {
          bronze: 'hsl(var(--league-bronze))',
          silver: 'hsl(var(--league-silver))',
          gold:   'hsl(var(--league-gold))',
        },
        cecr: {
          a1: 'hsl(var(--cecr-a1))',
          a2: 'hsl(var(--cecr-a2))',
          b1: 'hsl(var(--cecr-b1))',
          b2: 'hsl(var(--cecr-b2))',
          c1: 'hsl(var(--cecr-c1))',
          c2: 'hsl(var(--cecr-c2))',
        },
      },
      borderRadius: {
        sm:   "calc(var(--radius) - 8px)",   /* 8px */
        md:   "calc(var(--radius) - 6px)",   /* 10px */
        lg:   "var(--radius)",               /* 16px */
        xl:   "calc(var(--radius) + 4px)",   /* 20px */
        "2xl": "calc(var(--radius) + 8px)",  /* 24px */
        "3xl": "calc(var(--radius) + 8px)",  /* 24px — signature */
        "4xl": "calc(var(--radius) + 16px)", /* 32px — hero */
        "5xl": "calc(var(--radius) + 24px)", /* 40px */
      },
      boxShadow: {
        sm:      'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md:      'var(--shadow-md)',
        lg:      'var(--shadow-lg)',
        xl:      'var(--shadow-xl)',
        glow:    'var(--shadow-glow)',
        /* 3D buttons signature */
        '3d-blue':         '0 4px 0 0 hsl(var(--cia-blue-700)), 0 6px 14px -2px hsl(var(--cia-blue-500) / 0.35)',
        '3d-blue-active':  '0 1px 0 0 hsl(var(--cia-blue-700)), 0 2px 4px -2px hsl(var(--cia-blue-500) / 0.35)',
        '3d-gold':         '0 4px 0 0 hsl(var(--cia-gold-600)), 0 6px 14px -2px hsl(var(--cia-gold-500) / 0.40)',
        '3d-gold-active':  '0 1px 0 0 hsl(var(--cia-gold-600)), 0 2px 4px -2px hsl(var(--cia-gold-500) / 0.35)',
        '3d-success':      '0 4px 0 0 hsl(var(--success-600)), 0 6px 14px -2px hsl(var(--success-500) / 0.35)',
        '3d-red':          '0 4px 0 0 hsl(var(--cia-red-600)), 0 6px 14px -2px hsl(var(--cia-red-500) / 0.35)',
        /* Neutre : fond blanc + liseré ink — base des options QCM (M3) */
        '3d-neutral':        '0 4px 0 0 hsl(var(--ink-200)), 0 6px 14px -2px hsl(var(--ink-300) / 0.30)',
        '3d-neutral-active': '0 1px 0 0 hsl(var(--ink-200)), 0 2px 4px -2px hsl(var(--ink-300) / 0.30)',
        /* Legacy aliases (kept for prior code) */
        '3d-button-sm':    '0 2px 0 0 hsl(var(--cia-blue-700) / 0.35)',
        '3d-button-md':    '0 3px 0 0 hsl(var(--cia-blue-700) / 0.40)',
        '3d-button-lg':    '0 4px 0 0 hsl(var(--cia-blue-700) / 0.50)',
        '3d-gold-sm':      '0 2px 0 0 hsl(var(--cia-gold-600) / 0.40)',
        '3d-gold-md':      '0 3px 0 0 hsl(var(--cia-gold-600) / 0.50)',
        '3d-gold-lg':      '0 4px 0 0 hsl(var(--cia-gold-600) / 0.55)',
        /* Premium elevations */
        'elev-lg':  '0 24px 60px -20px hsl(var(--cia-blue-500) / 0.25), 0 8px 20px -10px hsl(var(--cia-blue-500) / 0.10)',
        'elev-xl':  '0 40px 90px -30px hsl(var(--cia-blue-500) / 0.30), 0 16px 40px -15px hsl(var(--cia-blue-500) / 0.12)',
        'elevated': 'var(--shadow-lg)',
        /* Glass + glow */
        'glass':         'inset 0 1px 0 hsl(0 0% 100% / 0.7), 0 8px 24px -8px hsl(var(--cia-blue-500) / 0.18)',
        'glass-strong':  '0 16px 48px -4px hsl(var(--cia-blue-500) / 0.25), 0 4px 16px -2px hsl(var(--cia-blue-500) / 0.12)',
        'glow-gold':     '0 0 0 6px hsl(var(--cia-gold-500) / 0.18), 0 0 40px 0 hsl(var(--cia-gold-500) / 0.45)',
        'glow-blue':     '0 0 0 6px hsl(var(--cia-spark-mid) / 0.18), 0 0 40px 0 hsl(var(--cia-spark-mid) / 0.55)',
      },
      backgroundImage: {
        'g-sun':     'linear-gradient(135deg, hsl(45 100% 83%) 0%, hsl(var(--cia-gold-300)) 45%, hsl(var(--cia-gold-500)) 100%)',
        'g-sea':     'linear-gradient(180deg, hsl(var(--cia-spark-mid)) 0%, hsl(var(--cia-blue-500)) 100%)',
        'g-dawn':    'linear-gradient(135deg, hsl(var(--cia-gold-500)) 0%, hsl(var(--cia-spark-light)) 60%, hsl(var(--cia-blue-500)) 100%)',
        'g-sunset':  'linear-gradient(135deg, hsl(var(--cia-red-500)) 0%, hsl(var(--cia-red-300)) 45%, hsl(var(--cia-gold-500)) 100%)',
        'g-mistral': 'linear-gradient(180deg, hsl(0 0% 100%) 0%, hsl(var(--cia-blue-50)) 100%)',
        'g-spark':   'radial-gradient(circle at 50% 35%, hsl(var(--cia-spark-light) / 0.55) 0%, hsl(var(--cia-spark-mid)) 55%, hsl(var(--cia-blue-700)) 100%)',
        'g-shine':   'linear-gradient(90deg, hsl(var(--cia-gold-500)) 0%, hsl(45 100% 83%) 50%, hsl(var(--cia-gold-500)) 100%)',
        /* Legacy gradient aliases */
        'gradient-sun':        'linear-gradient(135deg, hsl(var(--cia-gold-200)) 0%, hsl(var(--cia-gold-400)) 50%, hsl(var(--cia-gold-500)) 100%)',
        'gradient-sea':        'linear-gradient(180deg, hsl(var(--cia-blue-300)) 0%, hsl(var(--cia-blue-500)) 50%, hsl(var(--cia-blue-700)) 100%)',
        'gradient-dawn':       'linear-gradient(135deg, hsl(var(--cia-gold-300)) 0%, hsl(var(--cia-blue-500)) 100%)',
        'gradient-sunset':     'linear-gradient(135deg, hsl(var(--cia-red-300)) 0%, hsl(var(--cia-gold-400)) 100%)',
        'gradient-mistral':    'linear-gradient(180deg, hsl(0 0% 100%) 0%, hsl(var(--cia-blue-100)) 100%)',
        'gradient-premium':    'linear-gradient(135deg, hsl(var(--cia-blue-700)) 0%, hsl(var(--cia-blue-900)) 50%, hsl(var(--cia-blue-700)) 100%)',
        'gradient-gold-shine': 'linear-gradient(135deg, hsl(var(--cia-gold-300)) 0%, hsl(var(--cia-gold-500)) 50%, hsl(var(--cia-gold-300)) 100%)',
      },
      transitionTimingFunction: {
        'out-expo':    'var(--ease-out-expo)',
        'out-back':    'var(--ease-out-back)',
        'in-out-soft': 'var(--ease-in-out-soft)',
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in":  { from: { opacity: "0", transform: "translateY(10px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-up": { from: { opacity: "0", transform: "translateY(20px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { from: { opacity: "0", transform: "scale(0.9)" }, to: { opacity: "1", transform: "scale(1)" } },
        "bounce-in": {
          "0%":   { opacity: "0", transform: "scale(0.3)" },
          "50%":  { transform: "scale(1.05)" },
          "70%":  { transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "shake": {
          "0%, 100%":                          { transform: "translateX(0)" },
          "10%, 30%, 50%, 70%, 90%":           { transform: "translateX(-4px)" },
          "20%, 40%, 60%, 80%":                { transform: "translateX(4px)" },
        },
        "celebrate": {
          "0%":   { transform: "scale(1)" },
          "50%":  { transform: "scale(1.2) rotate(5deg)" },
          "100%": { transform: "scale(1) rotate(0)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1",   transform: "scale(1)" },
          "50%":      { opacity: "0.8", transform: "scale(1.05)" },
        },
        "progress-fill": { from: { width: "0%" }, to: { width: "var(--progress-width)" } },
        "count-up":      { from: { opacity: "0", transform: "translateY(10px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "float":     { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-6px)" } },
        "scale-pop": { from: { opacity: "0", transform: "scale(0.92)" }, to: { opacity: "1", transform: "scale(1)" } },
        "shimmer":   { from: { backgroundPosition: "-200% 0" }, to: { backgroundPosition: "200% 0" } },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 0 0 hsl(var(--cia-gold-500) / 0.4)" },
          "50%":      { boxShadow: "0 0 0 12px hsl(var(--cia-gold-500) / 0)" },
        },
        "streak-flame": {
          "0%, 100%": { transform: "rotate(-3deg) scale(1)" },
          "50%":      { transform: "rotate(3deg) scale(1.05)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
        "fade-in":   "fade-in 0.5s ease-out forwards",
        "slide-up":  "slide-up 0.5s ease-out forwards",
        "scale-in":  "scale-in 0.3s ease-out forwards",
        "bounce-in": "bounce-in 0.6s ease-out forwards",
        "shake":     "shake 0.5s ease-out",
        "celebrate": "celebrate 0.5s ease-out",
        "pulse-soft":     "pulse-soft 2s ease-in-out infinite",
        "progress-fill":  "progress-fill 1s ease-out forwards",
        "count-up":       "count-up 0.5s ease-out forwards",
        "float":          "float 3s ease-in-out infinite",
        "scale-pop":      "scale-pop 0.4s var(--ease-out-back)",
        "shimmer":        "shimmer 2s ease-in-out infinite",
        "glow-pulse":     "glow-pulse 2s ease-out infinite",
        "streak-flame":   "streak-flame 1.6s ease-in-out infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
